#!/usr/bin/env bash
# Generates INDEX.md — flat list of all problems, grouped by topic.
set -euo pipefail
# Pin collation: without it `sort` orders differently under en_US.UTF-8 vs C,
# so INDEX.md churns depending on whose machine regenerated it.
export LC_ALL=C
out=INDEX.md
total=$(find topics -name '*.md' ! -name 'README.md' | wc -l | tr -d ' ')
{
  echo "# INDEX — All Problems"
  echo
  echo "Flat, generated index of every problem file (grouped by topic). **Total: ${total} problems.**"
  echo "Generated by \`gen_index.sh\`. See [TAXONOMY.md](./TAXONOMY.md) for topic descriptions."
  echo
  for d in topics/*/; do
    slug=$(basename "$d")
    # topic display name from the topic README H1
    name=$(grep -m1 '^# ' "$d/README.md" 2>/dev/null | sed 's/^# //')
    [ -z "$name" ] && name="$slug"
    cnt=$(find "$d" -name '*.md' ! -name 'README.md' | wc -l | tr -d ' ')
    echo "## ${name} (${cnt})"
    echo
    echo "Dir: [\`${slug}\`](./topics/${slug}/)"
    echo
    for f in $(find "$d" -name '*.md' ! -name 'README.md' | sort); do
      fn=$(basename "$f")
      title=$(grep -m1 '^# ' "$f" | sed 's/^# //')
      [ -z "$title" ] && title="$fn"
      echo "- [${title}](./topics/${slug}/${fn})"
    done
    echo
  done
} > "$out"
echo "Wrote $out with $total problems."
